// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Microservice_Mercadolibre_Users_AWS",
    "version": "1"
  },
  "paths": {
    "/v1/db-connection": {
      "get": {
        "summary": "databaseTest",
        "description": "",
        "operationId": "databaseTest.get./v1/db-connection",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/list": {
      "get": {
        "summary": "getAllUsers",
        "description": "",
        "operationId": "getAllUsers.get./v1/users/list",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/id/{id}": {
      "get": {
        "summary": "getByIdUsers",
        "description": "",
        "operationId": "getByIdUsers.get./v1/users/id/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/nickname/{nickname}": {
      "get": {
        "summary": "getLikeNicknameUsers",
        "description": "",
        "operationId": "getLikeNicknameUsers.get./v1/users/nickname/{nickname}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "nickname",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/first-name/{firstName}": {
      "get": {
        "summary": "getLikeFirstNameUsers",
        "description": "",
        "operationId": "getLikeFirstNameUsers.get./v1/users/first-name/{firstName}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "firstName",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/last-name/{lastName}": {
      "get": {
        "summary": "getLikeLastNameUsers",
        "description": "",
        "operationId": "getLikeLastNameUsers.get./v1/users/last-name/{lastName}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "lastName",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/identification-type/{identificationType}": {
      "get": {
        "summary": "getLikeIdentificationTypeUsers",
        "description": "",
        "operationId": "getLikeIdentificationTypeUsers.get./v1/users/identification-type/{identificationType}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "identificationType",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/identification-number/{identificationNumber}": {
      "get": {
        "summary": "getLikeIdentificationNumberUsers",
        "description": "",
        "operationId": "getLikeIdentificationNumberUsers.get./v1/users/identification-number/{identificationNumber}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "identificationNumber",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/country-id/{countryId}": {
      "get": {
        "summary": "getLikeCountryIdUsers",
        "description": "",
        "operationId": "getLikeCountryIdUsers.get./v1/users/country-id/{countryId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "countryId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/email/{email}": {
      "get": {
        "summary": "getLikeEmailUsers",
        "description": "",
        "operationId": "getLikeEmailUsers.get./v1/users/email/{email}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/creation-date/{creationDate}": {
      "get": {
        "summary": "getLikeCreationDateUsers",
        "description": "",
        "operationId": "getLikeCreationDateUsers.get./v1/users/creation-date/{creationDate}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "creationDate",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/update-date/{updateDate}": {
      "get": {
        "summary": "getLikeUpdateDateUsers",
        "description": "",
        "operationId": "getLikeUpdateDateUsers.get./v1/users/update-date/{updateDate}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "updateDate",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/add-user/": {
      "post": {
        "summary": "addUser",
        "description": "",
        "operationId": "addUser.post./v1/users/add-user/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/update-user/{id}": {
      "put": {
        "summary": "updateUser",
        "description": "",
        "operationId": "updateUser.put./v1/users/update-user/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/v1/users/delete-user/{id}": {
      "delete": {
        "summary": "deleteUser",
        "description": "",
        "operationId": "deleteUser.delete./v1/users/delete-user/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/swagger/",
  "host": "http://127.0.0.1",
  "schemes": [
    "http",
    "https",
    "ws",
    "wss"
  ]
};